openapi: 3.0.3
info:
  title: HackLive - Hackathon Listing API
  description: A comprehensive API for managing and discovering hackathon events worldwide
  version: 1.0.0
  contact:
    name: HackLive Support
    url: https://dd94d512.hacklive-d2.pages.dev
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://dd94d512.hacklive-d2.pages.dev/api
    description: Production server
  - url: http://localhost:5000/api
    description: Development server

paths:
  /hackathons:
    get:
      summary: Get all hackathons
      description: Retrieve a list of all hackathon events ordered by creation date
      operationId: getHackathons
      tags:
        - Hackathons
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hackathon'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Create a new hackathon
      description: Create a new hackathon event (requires admin authentication)
      operationId: createHackathon
      tags:
        - Hackathons
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HackathonInput'
      responses:
        '201':
          description: Hackathon created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hackathon'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - invalid or missing credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/login:
    post:
      summary: Admin login
      description: Authenticate admin user and create session
      operationId: adminLogin
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/status:
    get:
      summary: Check authentication status
      description: Verify if current session is authenticated
      operationId: checkAuthStatus
      tags:
        - Authentication
      responses:
        '200':
          description: Authentication status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthStatus'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Hackathon:
      type: object
      required:
        - id
        - name
        - organizerName
        - startDate
        - endDate
        - location
        - format
        - description
        - status
        - tags
        - experienceLevel
      properties:
        id:
          type: integer
          description: Unique identifier for the hackathon
          example: 1
        name:
          type: string
          description: Name of the hackathon
          example: "Silicon Valley AI Summit"
        organizerName:
          type: string
          description: Name of the organizing entity
          example: "TechCorp Innovations"
        startDate:
          type: string
          format: date
          description: Start date of the hackathon
          example: "2024-03-15"
        endDate:
          type: string
          format: date
          description: End date of the hackathon
          example: "2024-03-17"
        location:
          type: string
          description: Location of the hackathon
          example: "USA, San Francisco"
        format:
          type: string
          enum: [In-person, Virtual, Hybrid]
          description: Format of the hackathon
          example: "In-person"
        description:
          type: string
          description: Detailed description of the hackathon
          example: "The premier AI hackathon on the West Coast. Build the next generation of AI applications with leading tech companies."
        prizePool:
          type: integer
          nullable: true
          description: Total prize pool amount in USD
          example: 50000
        registrationDeadline:
          type: string
          format: date
          nullable: true
          description: Registration deadline
          example: "2024-03-01"
        status:
          type: string
          enum: [Open, Closing Soon, Closed]
          description: Current status of the hackathon
          example: "Open"
        tags:
          type: array
          items:
            type: string
          description: Tags related to the hackathon theme/technology
          example: ["AI", "Machine Learning", "Data Science"]
        experienceLevel:
          type: string
          enum: [Beginner, Intermediate, Advanced, All Levels]
          description: Required experience level
          example: "Advanced"
        imageUrl:
          type: string
          nullable: true
          description: URL to hackathon image/logo
          example: null
        websiteUrl:
          type: string
          nullable: true
          description: Official website URL
          example: "https://svaisummit.com"
        createdAt:
          type: string
          format: date-time
          description: When the hackathon was created in the system
          example: "2025-05-31T02:35:57.000Z"

    HackathonInput:
      type: object
      required:
        - name
        - organizerName
        - startDate
        - endDate
        - location
        - format
        - description
        - experienceLevel
      properties:
        name:
          type: string
          description: Name of the hackathon
          example: "Berlin Blockchain Bootcamp"
        organizerName:
          type: string
          description: Name of the organizing entity
          example: "European Crypto Alliance"
        startDate:
          type: string
          format: date
          description: Start date of the hackathon
          example: "2024-04-20"
        endDate:
          type: string
          format: date
          description: End date of the hackathon
          example: "2024-04-22"
        location:
          type: string
          description: Location of the hackathon
          example: "Germany, Berlin"
        format:
          type: string
          enum: [In-person, Virtual, Hybrid]
          description: Format of the hackathon
          example: "Hybrid"
        description:
          type: string
          description: Detailed description of the hackathon
          example: "Explore the future of decentralized applications and blockchain technology in Europe's tech capital."
        prizePool:
          type: integer
          nullable: true
          description: Total prize pool amount in USD
          example: 25000
        registrationDeadline:
          type: string
          format: date
          nullable: true
          description: Registration deadline
          example: "2024-04-05"
        status:
          type: string
          enum: [Open, Closing Soon, Closed]
          description: Current status of the hackathon
          default: "Open"
          example: "Open"
        tags:
          type: array
          items:
            type: string
          description: Tags related to the hackathon theme/technology
          example: ["Blockchain", "Web3", "DeFi"]
        experienceLevel:
          type: string
          enum: [Beginner, Intermediate, Advanced, All Levels]
          description: Required experience level
          example: "Intermediate"
        imageUrl:
          type: string
          nullable: true
          description: URL to hackathon image/logo
          example: null
        websiteUrl:
          type: string
          nullable: true
          description: Official website URL
          example: "https://berlinblockchain.eu"

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: Admin email address
          example: "nameismike2002@gmail.com"
        password:
          type: string
          description: Admin password
          example: "Krushna@2002"

    LoginResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Login success status
          example: true
        message:
          type: string
          description: Success message
          example: "Login successful"

    AuthStatus:
      type: object
      properties:
        authenticated:
          type: boolean
          description: Current authentication status
          example: true

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
          example: "Failed to fetch hackathons"

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Basic authentication using admin email and password

tags:
  - name: Hackathons
    description: Operations related to hackathon events
  - name: Authentication
    description: Operations related to admin authentication

externalDocs:
  description: Visit HackLive
  url: https://dd94d512.hacklive-d2.pages.dev
