name = "hackathon-listing-app"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[build]
command = "npx vite build --outDir dist"

[[d1_databases]]
binding = "DB"
database_name = "hackathon-db"
database_id = "REPLACE_WITH_YOUR_ACTUAL_DATABASE_ID"

[env.production.d1_databases]
binding = "DB"
database_name = "hackathon-db"
database_id = "REPLACE_WITH_YOUR_ACTUAL_DATABASE_ID"

[vars]
ENVIRONMENT = "production"
