name = "hackathon-listing-app"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist/public"



[[d1_databases]]
binding = "DB"
database_name = "hackathon-db"
database_id = "57086ee6-17f3-4fbd-bdc1-7c9a89db0c14"

[[env.production.d1_databases]]
binding = "DB"
database_name = "hackathon-db"
database_id = "57086ee6-17f3-4fbd-bdc1-7c9a89db0c14"

[env.production.vars]
ENVIRONMENT = "production"

[vars]
ENVIRONMENT = "production"
