name = "hackathon-listing-app"
main = "functions/_middleware.ts"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "hackathon-db"
database_id = "57086ee6-17f3-4fbd-bdc1-7c9a89db0c14"

[env.production.d1_databases]
binding = "DB"
database_name = "hackathon-db"
database_id = "57086ee6-17f3-4fbd-bdc1-7c9a89db0c14"

[vars]
ENVIRONMENT = "production"
